<?xml version="1.0"?>
<package format="3">
  <name>my_factory</name>
  <version>0.0.0</version>
  <description>Autonomous Warehouse Robot Project</description>
  <maintainer email="abdulrahman@todo.todo">abdulrahman</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>slam_toolbox</depend>
  <depend>robot_state_publisher</depend>
  <depend>joint_state_publisher</depend>
  <depend>xacro</depend>
  <depend>nav2_bringup</depend>
  <depend>navigation2</depend>
  <depend>nav2_simple_commander</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>