slam_toolbox:
  ros__parameters:

    # --- إعدادات وضع التشغيل ---
    mode: mapping
    map_start_pose: [0.0, 0.0, 0.0]
    map_start_at_dock: true

    # --- الإطارات المرجعية (مطابقة لنتائج view_frames) ---
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint # مرتبط بـ base_link في الـ TF
    scan_topic: /scan 
    use_sim_time: true

    # --- إعدادات التزامن ---
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.05 
    map_update_interval: 5.0      
    resolution: 0.05            
    max_laser_range: 20.0         
    minimum_time_interval: 0.2
    transform_timeout: 0.5        
    tf_buffer_duration: 30.0

    # --- إعدادات المطابقة (Scan Matching) - تم تعديلها لتناسب وجود الـ IMU ---
    use_scan_matching: true
    use_scan_barycenter: true
    
    # ارفعنا القيم قليلاً لضمان عدم حدوث "قفزات" في الخريطة بسبب الاهتزاز
    minimum_travel_distance: 0.3   # لا يحدث الخريطة إلا بعد حركة 30 سم
    minimum_travel_heading: 0.1    # لا يحدث الخريطة إلا بعد دوران 0.1 راديان (حوالي 6 درجات)
    
    scan_matching_stats_iteration_limit: 50 

    # --- إعدادات البحث عن الربط (Scan-to-Map Matching) ---
    link_match_maximum_distance: 0.5
    link_scan_maximum_distance: 1.5
    
    # --- إغلاق الحلقات (Loop Closing) ---
    do_loop_closing: true
    loop_closure_search_radius: 15.0 
    loop_closure_search_maximum_distance_hypothesis: 4.0
    loop_closure_min_chain_size: 20
    loop_closure_min_score: 0.5
    
    # --- إعدادات الذاكرة ---
    stack_size_to_use: 40000000